- name: Copy join command from ansible host to the master nodes
  copy:
    src: /tmp/kubernetes_master_join_command
    dest: /tmp/kubernetes_master_join_command
    mode: 0777
 
- name: Join the master nodes to the cluster
  command: bash /tmp/kubernetes_master_join_command
  register: join_status

- name: Print the join status
  debug: msg="{{ join_status }}"
